### ISSUE TITLE
询问数据集

### ISSUE THREAD

**Issue by youyou098888** [huangxiangzhou/NLPCC2016KBQA#1]
您好，请问还有NLPCC-ICCPOL 2016 KBQA原始的数据集了么？

**Comment by supergyz** [comment]
@youyou098888 请问你找到原始数据集了吗

**Comment by huangxiangzhou** [comment]
http://tcci.ccf.org.cn/conference/2017/taskdata.php

**Comment by mazicwong** [comment]
@supergyz 请问你找到原始数据集了吗，16年的

**Comment by huangxiangzhou** [comment]
http://tcci.ccf.org.cn/conference/2017/taskdata.php

2019-02-17 12:11:29mazic <notifications@github.com>写道：

@supergyz 请问你找到原始数据集了吗，16年的

**Comment by huangxiangzhou** [comment]
http://tcci.ccf.org.cn/conference/2017/taskdata.php


-----原始邮件-----
发件人:mazic <notifications@github.com>
发送时间:2019-02-17 12:11:29 (星期日)
收件人: huangxiangzhou/NLPCC2016KBQA <NLPCC2016KBQA@noreply.github.com>
抄送: huangxiangzhou <huangxiangzhou@zju.edu.cn>, "State change" <state_change@noreply.github.com>
主题: Re: [huangxiangzhou/NLPCC2016KBQA] 询问数据集 (#1)



@supergyz 请问你找到原始数据集了吗，16年的

**Comment by mazicwong** [comment]
我已经下载了2017年的数据，看到里面包含了2016年的数据，感谢！
